parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - name: BuildConfiguration
    value: release
  - group: BUILD Management Resources
  workspace:
      clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Worker'
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/DAS.Employer.Finance.Jobs/DAS.Employer.Finance.Jobs/${{ parameters.SolutionBaseName }}.csproj
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: ArchiveFiles@2
    displayName: 'Archive Worker Package'
    inputs:
      rootFolderOrFile: '$(build.artifactstagingdirectory)/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(build.artifactstagingdirectory)/${{ parameters.SolutionBaseName }}.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: ${{ parameters.SolutionBaseName }}